### ISSUE TITLE
Allow payment from a Safe Multisig

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/invoicing-template#43]
# Problem

It should be possible to pay a request using a Safe.

We already enabled the Safe payment type in Web3Onboard but it doesn't appear on the Web3Onboard dialog.

# Considerations

* Do we provide a UI for the initial signer?
* Do we provide a UI for the subsequent signers?

**Comment by MantisClone** [comment]
@sstefdev reported that this already works.

**Comment by MantisClone** [comment]
Action Item: 
- [ ] @sstefdev to share a video of it working

**Comment by MantisClone** [comment]
Added instructions to the docs ✅ 
https://docs.request.network/building-blocks/templates/pay-from-safe-multisig

**Comment by aimensahnoun** [comment]
It is possible to make a payment from a Safe Multisig using the invoicing template: 

https://github.com/user-attachments/assets/eee0bd88-9fe0-442d-b9fc-d00fd64b3792
