### ISSUE TITLE
Increase performance of invoicing app

### ISSUE THREAD

**Issue by aimensahnoun** [RequestNetwork/invoicing-template#46]
### Problem:

The invoicing template has low performance - loading the components takes a long time. This is NOT talking about the time to load the Requests. 
https://pagespeed.web.dev/analysis/https-invoicing-request-network/dx4tgdpzfw?form_factor=mobile
![image (2)](https://github.com/user-attachments/assets/dc5deab2-054a-4793-bdc4-ebaa6414d638)

**Comment by MantisClone** [comment]
@rodrigopavezi proposed "lazy loading" the components.

**Comment by MantisClone** [comment]
@sstefdev said he improved the score

**Comment by sstefdev** [comment]
This is updated performance:

- Mobile: ![Image](https://github.com/user-attachments/assets/0602b623-675c-4557-9899-ac7c7439bd0f)
- Desktop: ![Image](https://github.com/user-attachments/assets/295b177c-4818-4311-8569-6b0367553418)
